// This file is generated by scripts/sync-db-migrations.ts.
// Do not edit manually.
import migration0000 from "../../../drizzle/0000_init.sql" with { type: "text" };
import migration0001 from "../../../drizzle/0001_add-indexes.sql" with { type: "text" };

export const generatedMigrations = [migration0000, migration0001] as const;
