import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type JournalEntry = {
  tag: string;
};

type DrizzleJournal = {
  entries: JournalEntry[];
};

const toIdentifier = (index: number): string => {
  return `migration${String(index).padStart(4, "0")}`;
};

const run = async (): Promise<void> => {
  const projectRoot = process.cwd();
  const journalPath = resolve(projectRoot, "drizzle/meta/_journal.json");
  const outputPath = resolve(projectRoot, "src/lib/db/generated-migrations.ts");

  const rawJournal = await readFile(journalPath, "utf8");
  const journal = JSON.parse(rawJournal) as DrizzleJournal;
  const entries = journal.entries ?? [];

  if (entries.length === 0) {
    throw new Error("No migration entries found in drizzle/meta/_journal.json");
  }

  const importLines: string[] = [];
  const migrationNames: string[] = [];

  for (const [index, entry] of entries.entries()) {
    const identifier = toIdentifier(index);
    importLines.push(
      `import ${identifier} from "../../../drizzle/${entry.tag}.sql" with { type: "text" };`,
    );
    migrationNames.push(identifier);
  }

  const output = [
    "// This file is generated by scripts/sync-db-migrations.ts.",
    "// Do not edit manually.",
    ...importLines,
    "",
    `export const generatedMigrations = [${migrationNames.join(", ")}] as const;`,
    "",
  ].join("\n");

  await writeFile(outputPath, output, "utf8");
};

await run();
